version: "3.8"

services:
  strapi_v5:
    # Docker Swarm não suporta build em stacks. Use uma imagem publicada em registry.
    # Ajustado para seu namespace Docker Hub
    image: docker.io/marcelolealhub/imobai-strapi-v5:5.30
    container_name: strapi_v5
    environment:
      NODE_ENV: production

      # Database (matches your Postgres 17 stack service name "postgres")
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres17_postgres
      DATABASE_PORT: 5432 # dentro da rede Docker o Postgres escuta em 5432
      DATABASE_NAME: imobdb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Mfcd62Mfcd62

      # Security secrets (inserir via Portainer Environment/Secrets)
      ADMIN_JWT_SECRET: +fwF3vQ9xpsMFgmEs34fVgwmvYSlKkQhuxnJqFmkJRfsErRxDDYcYNOCNOy91n+nQPIPk0aOiBCw/g2Xe+wQgA==
      API_TOKEN_SALT: tpkbf4fEEnRyZxCEjzZM+8r1D+Nc3sXjVRKg2YtWm3qJHn+qX9PG/vuxLH4v/bDW6KlMBLZ75oSo/B4WjpkGyA==
      APP_KEYS: q4BMocPYnSrfcFp7mTJhmhrkCO3kOlb0WsVGwhpDGnRgWrf3ARZdT0fDTcEjQYyv2rjcl24Qgt0UtnQMw+Ma9Q==,zJwfscV5FKaKyA0QDlAlmo2Dgl3/KQt9u8N+8lEOzZiLv4zZpUnP5NgOHGI1R/Z9F338yBHiKG/kt8SGz4C6IA==,geslTVWSSzHDf9cyH+gHxeivZ0jWp4G03KdWmUa9SzBG9bRt8s7RL+/gstkifSF9JAUectK7u9AoEfTML2TqCg==,IqUhJ96ntgH0CxyCjepVUSna1Lh8b7sawjci6h+IZKSMc0sJqsMqEv0oQNTjNBvalKlV4S/qubW6EbtdojF2pQ==
      JWT_SECRET: MO+VDegjFVf3sv1/rQz26Db8hihLXzm8D/o7QyGL6KdOSew52+SVIJ5soJDecujirXii9/JwfB7Vpw2kA26tpw==

      # Uploads S3/MinIO (mantendo seus parâmetros atuais)
      AWS_ACCESS_KEY_ID: dJvus2drgD1Uwd66bnu1
      AWS_SECRET_ACCESS_KEY: a23r3JwsjhGl8o3osxmd9INB7zNQScd9k6aymYqc
      AWS_REGION: us-east-1
      AWS_S3_BUCKET: bloco
      AWS_S3_ENDPOINT: https://imobs3.advancedbot.com.br
      AWS_S3_FORCE_PATH_STYLE: true

    networks:
      - network_public

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.strapi_v5.rule=Host(`imob.advancedbot.com.br`) # ajuste o domínio se necessário
        - traefik.http.routers.strapi_v5.entrypoints=websecure
        - traefik.http.routers.strapi_v5.tls.certresolver=letsencryptresolver
        - traefik.http.services.strapi_v5.loadbalancer.server.port=1337
        - traefik.http.services.strapi_v5.loadbalancer.passHostHeader=true

    restart: unless-stopped

networks:
  network_public:
    external: true
    name: network_public